=== yw-masterthesis/ddd-generator-demo/domain-model.dtd
<!ELEMENT domain (context+)>
<!ATTLIST domain name ID #REQUIRED>
<!ELEMENT context (aggregate|entity|value-object|enum|service|event)*>
<!ATTLIST context name ID #REQUIRED>
<!ELEMENT aggregate (root, identity?, entity*, value-object*)>
<!ATTLIST aggregate name ID #REQUIRED>
<!ELEMENT root EMPTY>
<!ATTLIST root name ID #REQUIRED>
<!ELEMENT identity EMPTY>
<!ATTLIST identity name ID #IMPLIED>
<!ATTLIST identity ref IDREF #IMPLIED>
<!ELEMENT entity EMPTY>
<!ATTLIST entity name ID #REQUIRED>
<!ELEMENT value-object EMPTY>
<!ATTLIST value-object name ID #REQUIRED>
<!ELEMENT enum EMPTY>
<!ATTLIST enum name ID #REQUIRED>
<!ELEMENT service EMPTY>
<!ATTLIST service name ID #REQUIRED>
<!ELEMENT event EMPTY>
<!ATTLIST event name ID #REQUIRED>

=== yw-masterthesis/ddd-generator-demo/library.domain-model.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE domain SYSTEM "domain-model.dtd">
<domain name="Library">
  <context name="Catalogue">
    <entity name="Book"></entity>
    <entity name="BookInstance"></entity>
    <value-object name="BookId"></value-object>
    <value-object name="ISBN"></value-object>
    <value-object name="Title"></value-object>
    <value-object name="Author"></value-object>
    <enum name="BookType"></enum>
    <service name="CatalogueService"></service>
    <event name="BookInstanceAddedToCatalogue"></event>
  </context>
</domain>
